### ISSUE TITLE
Segfault caused by accessing freed memory

### ISSUE THREAD

**Issue by omerbenamram** [libyal/libfsntfs#10]
Hi,

I was working on writing rust bindings for `libfsntfs` (https://github.com/omerbenamram/libfsntfs-sys), and I've found a rather strange segfault on one of my tests.

I'm able to reproduce to reproduce this in the provided python bindings python (latest pypi release).

I'm using a small ntfs sample for this test.
You can download it from here if needed:
https://github.com/omerbenamram/libfsntfs-sys/blob/master/examples/ntfs-img-kw-1.dd

This code works without any problems:
```python
import pyfsntfs

def main():
    sample = open("<path_to_sample>", "rb")
    vol = pyfsntfs.open(sample)
    for file_entry in vol.file_entries:
        print(list(file_entry.attributes))
```

But this version segfaults:
```python
import pyfsntfs

def main():
    sample = open("<path_to_sample>", "rb")
    vol = pyfsntfs.open(sample)
    # now saved as a variable
    entries = list(vol.file_entries)
    for file_entry in entries:
        print(list(file_entry.attributes))
```

From what I've tried to debug in my rust bindings, for some reason the `internal_file_entry->mft_entry` is pointing to freed memory, where `file_entry` was never freed on the rust side (`libfsntfs_file_entry_free` was never called).

Note that other members of the struct are still valid references.

![image](https://user-images.githubusercontent.com/2467993/55073787-53ef8280-5097-11e9-86f6-375fd9171d37.png)

**EDIT**: I've tried to see where mft entries are freed, and it seems that it has something to do with the cache mechanism.

Removing the call to `internal_cache_value->value_free_function` in https://github.com/libyal/libfcache/blob/master/libfcache/libfcache_cache_value.c#L477 stops the segfaults (but probably leaks memory?)

Thanks again for the library! :)

**Comment by joachimmetz** [comment]
Thx for the report, note that the code is still considered experimental, I'll have a look as soon as time permits.

**Comment by joachimmetz** [comment]
I've done a major overhaul recently, I opt to check the latest master to see if the issue has been addressed.

**Comment by joachimmetz** [comment]
Closing for now, reopen if issue persists
