### ISSUE TITLE
Documents about this library

### ISSUE THREAD

**Issue by Ax2401** [libyal/libfsntfs#11]
hi, 
It seems you put the NTFS document in the repo , but threr is no doucuments about this library?

**Comment by joachimmetz** [comment]
This project is experimental and a work in progress

The current available documentation:
* https://github.com/libyal/libfsntfs/blob/master/README
* https://github.com/libyal/libfsntfs/wiki

Any specific documentation you were looking for?

**Comment by joachimmetz** [comment]
No response from OP closing issue
