### ISSUE TITLE
about path formats?

### ISSUE THREAD

**Issue by Ax2401** [libyal/libfsntfs#12]
Hi,

Is there documents about path for libfsntfs_volume_open?

I tried  \\\\.\\D:  ,  \\\\.\\D:\\ , d: , d:\\  , all failed.  , the error info is :  "libcpath_path_get_full_path unable to retrieve number of path string segments."

**Comment by Ax2401** [comment]
I tried  \\device\\harddiskvolume3    , failed too.

**Comment by joachimmetz** [comment]
`\\.\D:\ ` and `D:\` point to the root of the live file system on Windows
`D:` points to the CWD on drive D

`\\.\D:` should work, need to have a look why not but note libfsntfs is experimental and intended to run on image files (copies of NTFS) **not** on live mounted file systems.

**Comment by joachimmetz** [comment]
No response from OP closing issue
