### ISSUE TITLE
Documentation of mounting (fsntfsmount) is not the same than what happens

### ISSUE THREAD

**Issue by aapo** [libyal/libfsntfs#17]
Documentation [ https://github.com/libyal/libfsntfs/wiki/Mounting ] says:

    fsntfsmount -o $(( 1024 * 512 )) image.raw /mnt/fuse
    This will expose a file system contained in the NTFS volume.
    /mnt/fuse/fsntfs1

For me, this mounts the filesystem to the /mnt/fuse/.

And _mount_ shows it as:

    /dev/fuse on /mnt/fuse type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)

I would like to have _/mnt/fuse/fsntfs1_ as a device file, and run _mount -o loop,ro /mnt/fuse/fsntfs1 /mnt/file_system_ by myself.

I tested libfsntfs-experimental-20200505 and libfsntfs-experimental-20200506 on Ubuntu-18.04:

     ldd installed/bin/fsntfsmount
        linux-vdso.so.1 (0x00007fffe2bfc000)
        libfuse.so.2 => /lib/x86_64-linux-gnu/libfuse.so.2 (0x00007fb2e898b000)
        libfsntfs.so.1 => /home/user/libfsntfs/installed/lib/libfsntfs.so.1 (0x00007fb2e8615000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb2e83f6000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb2e8005000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb2e7e01000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb2e8e5b000)

**Comment by joachimmetz** [comment]
@aapo thx for the report. I'll have a look when time permits, but it looks like the documentation needs some updating. fsntfsmount should expose the file system hierarchy. 

> I would like to have /mnt/fuse/fsntfs1 as a device file, and run mount -o loop,ro /mnt/fuse/fsntfs1 /mnt/file_system by myself.

you don't need fsntfsmount for this, just run ntfs3g mount directly on your image

**Comment by joachimmetz** [comment]
Documentation updated https://github.com/libyal/libfsntfs/wiki/Mounting

**Comment by aapo** [comment]
I have image with WOF and ntfs-3g can't handle it. It can handle it ntfs-3g-system-compression -plugin).

But I have another issue with the same image: ntfs-3g (+ system-compression). Files in C:\System Volume Information\ are not zero sized (e.g 544MB), but they contains only zeroes (0x00)
Checked with hd (it combines identical continues rows)

    hd mount_point_with_mount/System\ Volume\ Information/{*}{*} 
    00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
    *
    35374000


But they are not empty files:

    hd mounted_with_libfsntfs/System\ Volume\ Information/{*}{*}  | wc
    49589613 890254786 3884241591

**Comment by joachimmetz** [comment]
@aapo I don't fully understand your last update.

Are saying that the VSS metadata files (https://github.com/libyal/libvshadow/blob/master/documentation/Volume%20Shadow%20Snapshot%20(VSS)%20format.asciidoc#1-overview) exposed by libfsntfs show data but those exposed by ntfs-3g are not?

**Comment by aapo** [comment]
Just that I'm saying.

And then libshadow shows:

    Volume Shadow Snapshot information:
           Number of stores:       0

**Comment by joachimmetz** [comment]
libvshadow looks at the volume layer not the NTFS layer so those are not necessarily related.

**Comment by aapo** [comment]
Little bit more information: With Sleuthkit's icat I got (broken) files with only zeroes:

    icat image.dd -o 1026048 39-128-1 > VSS1
    icat image.dd -o 1026048 128-128-1 > VSS2

Only filesizes are correct.

**Comment by joachimmetz** [comment]
Can you provide the details from fsntfsinfo and istat

**Comment by aapo** [comment]
fsntfsinfo  -o $((512*1026048)) image.dd
    fsntfsinfo 20200120
    
    Windows NT File System information:
    
    Volume information:
            Name                            : BASE
            Version                         : 3.1
            Serial number                   : 94923ff5923fdb06
            Bytes per sector                : 512
            Cluster block size              : 4096
            MFT entry size                  : 1024
            Index entry size                : 4096
    
    istat  -o 1026048 image.dd 39-128-1
    
    MFT Entry Header Values:
    Entry: 39        Sequence: 35
    $LogFile Sequence Number: 8925565307
    Allocated File
    Links: 2
    
    $STANDARD_INFORMATION Attribute Values:
    Flags: Hidden, System, Archive
    Owner ID: 0
    Security ID: 1698  (S-1-5-32-544)
    Last User Journal Update Sequence Number: 3255444568
    Created:        2019-02-27 09:03:02.966260100 (EET)
    File Modified:  2019-02-27 11:28:31.656333900 (EET)
    MFT Modified:   2019-02-27 11:28:31.656333900 (EET)
    Accessed:       2019-02-27 09:03:02.966260100 (EET)
    
    $FILE_NAME Attribute Values:
    Flags: Hidden, System, Archive
    Name: {673e7cc9-3a5c-11e9-b813-901b0e4d36dd}{3808876b-c176-4e48-b7ae-04046e6cc752}
    Parent MFT Entry: 86745         Sequence: 2
    Allocated Size: 322387968       Actual Size: 322387968
    Created:        2019-02-27 09:03:02.966260100 (EET)
    File Modified:  2019-02-27 11:28:31.656333900 (EET)
    MFT Modified:   2019-02-27 11:28:31.656333900 (EET)
    Accessed:       2019-02-27 09:03:02.966260100 (EET)
    
    Attributes: 
    Type: $STANDARD_INFORMATION (16-0)   Name: N/A   Resident   size: 72
    Type: $FILE_NAME (48-3)   Name: N/A   Resident   size: 82
    Type: $FILE_NAME (48-2)   Name: N/A   Resident   size: 218
    Type: $DATA (128-1)   Name: N/A   Non-Resident   size: 322387968  init_size: 0
    30306112 0 0 0 0 0 0 0 
    0 0 0 0 0 0 0 0 
    0 0 0 0 0 0 0 0 
    0 0 0 0 0 0 0 0 
    0 0 0 0 0 0 0 0 
    ...(rest omitted)
    
    
    istat  -o 1026048 image.dd 128-128-1 
    
    MFT Entry Header Values:
    Entry: 128        Sequence: 9
    $LogFile Sequence Number: 8925564821
    Allocated File
    Links: 2
    
    $STANDARD_INFORMATION Attribute Values:
    Flags: Hidden, System, Archive
    Owner ID: 0
    Security ID: 1698  (S-1-5-32-544)
    Last User Journal Update Sequence Number: 3255444352
    Created:        2019-02-27 11:28:31.382343700 (EET)
    File Modified:  2019-02-27 11:28:31.413587300 (EET)
    MFT Modified:   2019-02-27 11:28:31.413587300 (EET)
    Accessed:       2019-02-27 11:28:31.382343700 (EET)
    
    $FILE_NAME Attribute Values:
    Flags: Hidden, System, Archive
    Name: {673e82e7-3a5c-11e9-b813-901b0e4d36dd}{3808876b-c176-4e48-b7ae-04046e6cc752}
    Parent MFT Entry: 86745         Sequence: 2
    Allocated Size: 570425344       Actual Size: 570425344
    Created:        2019-02-27 11:28:31.382343700 (EET)
    File Modified:  2019-02-27 11:28:31.413587300 (EET)
    MFT Modified:   2019-02-27 11:28:31.413587300 (EET)
    Accessed:       2019-02-27 11:28:31.382343700 (EET)
    
    Attributes: 
    Type: $STANDARD_INFORMATION (16-0)   Name: N/A   Resident   size: 72
    Type: $FILE_NAME (48-3)   Name: N/A   Resident   size: 82
    Type: $FILE_NAME (48-2)   Name: N/A   Resident   size: 218
    Type: $DATA (128-1)   Name: N/A   Non-Resident   size: 570425344  init_size: 0
    30445376 0 0 0 0 0 0 0 
    0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 
    0 0 0 0 0 0 0 0  
    (rest omitted)

**Comment by joachimmetz** [comment]
Can you use a more recent version of libfsntfs, there have been many changes since 20200120.

**Comment by aapo** [comment]
fsntfsinfo -o $((512*1026048)) image.dd 
    fsntfsinfo 20200515
    
    Windows NT File System information:
    
    Volume information:
            Name                            : BASE
            Version                         : 3.1
            Serial number                   : 94923ff5923fdb06
            Bytes per sector                : 512
            Cluster block size              : 4096
            MFT entry size                  : 1024
            Index entry size                : 4096

**Comment by joachimmetz** [comment]
can you also check your "System Volume Information" files again, is there still a difference?

Also could you use `fsntfsinfo -o $((512*1026048)) -E 128 image.dd` to get information about the specific MFT entry.

**Comment by aapo** [comment]
With fsntfsmount 20200515 "System Volume Information" files contains only zeroes, so it works same than ntfs-3g and icat. I still think this is error, and these files really contains data.

    fsntfsinfo 20200515
    
    MFT entry: 128 information:
            Is allocated                    : true
            File reference                  : 128-9
            Base record file reference      : Not set (0)
            Journal sequence number         : 8925564821
            Number of attributes            : 4
    
    Attribute: 1
            Type                            : $STANDARD_INFORMATION (0x00000010)
            Creation time                   : Feb 27, 2019 09:28:31.382343700 UTC
            Modification time               : Feb 27, 2019 09:28:31.413587300 UTC
            Access time                     : Feb 27, 2019 09:28:31.382343700 UTC
            Entry modification time         : Feb 27, 2019 09:28:31.413587300 UTC
            Owner identifier                : 0
            Security descriptor identifier  : 1698
            Update sequence number          : 3255444352
            File attribute flags            : 0x00000026
                    Is hidden (FILE_ATTRIBUTE_HIDDEN)
                    Is system (FILE_ATTRIBUTE_SYSTEM)
                    Should be archived (FILE_ATTRIBUTE_ARCHIVE)
    
    Attribute: 2
            Type                            : $FILE_NAME (0x00000030)
            Parent file reference           : 86745-2
            Creation time                   : Feb 27, 2019 09:28:31.382343700 UTC
            Modification time               : Feb 27, 2019 09:28:31.413587300 UTC
            Access time                     : Feb 27, 2019 09:28:31.382343700 UTC
            Entry modification time         : Feb 27, 2019 09:28:31.413587300 UTC
            File attribute flags            : 0x00000026
                    Is hidden (FILE_ATTRIBUTE_HIDDEN)
                    Is system (FILE_ATTRIBUTE_SYSTEM)
                    Should be archived (FILE_ATTRIBUTE_ARCHIVE)
            Name space                      : DOS (2)
            Name                            : {673E8~1
    
    Attribute: 3
            Type                            : $FILE_NAME (0x00000030)
            Parent file reference           : 86745-2
            Creation time                   : Feb 27, 2019 09:28:31.382343700 UTC
            Modification time               : Feb 27, 2019 09:28:31.413587300 UTC
            Access time                     : Feb 27, 2019 09:28:31.382343700 UTC
            Entry modification time         : Feb 27, 2019 09:28:31.413587300 UTC
            File attribute flags            : 0x00000026
                    Is hidden (FILE_ATTRIBUTE_HIDDEN)
                    Is system (FILE_ATTRIBUTE_SYSTEM)
                    Should be archived (FILE_ATTRIBUTE_ARCHIVE)
            Name space                      : Windows (1)
            Name                            : {673e82e7-3a5c-11e9-b813-901b0e4d36dd}{3808876b-c176-4e48-b7ae-04046e6cc752}
    
    Attribute: 4
            Type                            : $DATA (0x00000080)
            Data VCN range                  : 0 - 139263
            Data size                       : 570425344 bytes
            Data flags                      : 0x0000

**Comment by joachimmetz** [comment]
>  I still think this is error, and these files really contains data.

Not really, as you can see in the istat output:

`Type: $DATA (128-1)   Name: N/A   Non-Resident   size: 570425344  init_size: 0`

init_size: 0 means there is data stored in the data runs, but it is not supposed to be used you can read more about that here: https://github.com/log2timeline/dfvfs/issues/230. You can compare this behavior against the Windows NTFS driver if you want. The data that is stored in the data runs is at best to be treated as slack for such file. 

However these are special files, since they are related to VSS. It looks like your VSS catalog is missing hence libvshadow does not find the stores.

**Comment by aapo** [comment]
Ok, thanks, we went little bit off-topic. If I found more information relating these VSS-files I will open another issue (maybe to the libshadow then).

**Comment by joachimmetz** [comment]
@aapo you are very likely missing data, this is not a bug but the state of your data. See https://github.com/libyal/libvshadow/pull/18 and search for recovering a VSS catalog for more detail.
