### ISSUE TITLE
handling unknown data within the attribute_list

### ISSUE THREAD

**Issue by shen1l** [libyal/libfsntfs#19]
- I have encountered a issue when parsing data within the attribute_list, the data looks unlike a valid attribute .

- here is how the data looks like in 010 editor
![image](https://user-images.githubusercontent.com/10751634/94091261-67290d00-fe4a-11ea-9318-08928d7fcfd4.png)

-  here is visual studio view
![image](https://user-images.githubusercontent.com/10751634/94091798-c1769d80-fe4b-11ea-906b-71f4b4d177cb.png)
![image](https://user-images.githubusercontent.com/10751634/94091914-0a2e5680-fe4c-11ea-9fcf-c04daaee8756.png)

**Comment by shen1l** [comment]
- my mistake,the issue was because the mft entry is not in used
![image](https://user-images.githubusercontent.com/10751634/94092410-46ae8200-fe4d-11ea-81d8-dd5a11f32181.png)

**Comment by shen1l** [comment]
- my code before fixed
![image](https://user-images.githubusercontent.com/10751634/94098550-6d73b500-fe5b-11ea-96ca-dc94be65ae63.png)
- my code after fixed: looks a bit urgly and brings some unnecessary read/validation code logic
![image](https://user-images.githubusercontent.com/10751634/94098868-2c2fd500-fe5c-11ea-84dc-8c7784759d03.png)
- maybe a fixed is still needed for this library ?
![image](https://user-images.githubusercontent.com/10751634/94099196-f3443000-fe5c-11ea-8293-b411abc78f35.png)

**Comment by joachimmetz** [comment]
@shen1l can you provide a description of what you are trying to accomplish and what issue you are running into. I have a hard time understanding the current "dump" of screenshots

**Comment by shen1l** [comment]
- what I wanna do is to enumerate the mft entries, I used "libfsntfs_volume_get_file_entry_by_index" to get a file entry,but it returns 0 when the specific mft entry is not allocated. 
```
for (uint64_t file_entry_index = 0;
		file_entry_index < number_of_file_entries;
		file_entry_index++)
	{	
		unique_libfsntfs_file_entry_t file_entry;

               // it returns 0 if this is not an allocated mft entry which is not expected
		RETURN_HR_IF(E_FAIL, libfsntfs_volume_get_file_entry_by_index(
			volume.get(),
			file_entry_index,
			&file_entry,
			&error) != 1);

          // more code ...
}
```

**Comment by joachimmetz** [comment]
> but it returns 0 when the specific mft entry is not allocated.

which version of libfsntfs are you using?

**Comment by shen1l** [comment]
> > but it returns 0 when the specific mft entry is not allocated.
> 
> which version of libfsntfs are you using?

20200726

**Comment by joachimmetz** [comment]
I opt to use a more recent version. Note that this project has an experimental status and is under active development.
