### ISSUE TITLE
Dead links in references (appendix A)

### ISSUE THREAD

**Issue by Sim4n6** [libyal/libfsntfs#22]
Some dead links in the "_Appendix A: References_" of the documentation such as **RUSSON05** or **MEDEIROS08**

**Comment by joachimmetz** [comment]
thx for the report I'll have a look when I do the next update

**Comment by joachimmetz** [comment]
Addressed in https://github.com/libyal/libfsntfs/commit/7ace95123fee2f3211da68364286269112398fb6, closing issue
