### ISSUE TITLE
Unable to find release of version 20190104

### ISSUE THREAD

**Issue by vitacell** [libyal/libfsntfs#23]
Why you removed old versions, why to break things? Now I can't to download, and the newer version won't compile.

https://slackbuilds.org/repository/14.2/libraries/libfsntfs/
https://github.com/libyal/libfsntfs/releases/download/20190104/libfsntfs-experimental-20190104.tar.gz

**Comment by joachimmetz** [comment]
First of all this project is still experimental as indicated in the README. 

> Why you removed old versions, why to break things?

What am I breaking?

> Now I can't to download, and the newer version won't compile.

If you want to use a previous version, why can't you check it out of the git history?

>  Now I can't to download, and the newer version won't compile.

The current version (HEAD) is compiling fine on the CI test environment. What issue are you running into?

**Comment by vitacell** [comment]
I just want to compile, but both versions won't copile, these stucks at some random point like this one:

https://dpaste.org/mcbj

**Comment by joachimmetz** [comment]
What's with that snippet? it just contains a bunch of path names.

Can you be a bit more explicit? I cannot help you if you do not clearly explain to me what you are trying to accomplish and how. And what issues you are running into.

1. how are you downloading the source?
2. how are you compiling the source?
3. What error do you get?
4. Any relevant files like config.log that you could provide?

Also see: https://github.com/libyal/libfsntfs/wiki/Building

**Comment by vitacell** [comment]
1. How I download? https://github.com/libyal/libfsntfs/releases and then pressing on "libfsntfs-experimental-20201115.tar.gz" for download.

2. uname -a
Linux desktop 4.4.227 #2 SMP Thu Jun 11 15:07:16 CDT 2020 x86_64 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz GenuineIntel GNU/Linux

gcc -v
Leyendo especificaciones de /usr/lib64/gcc/x86_64-slackware-linux/5.5.0/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-slackware-linux/5.5.0/lto-wrapper
Objetivo: x86_64-slackware-linux
Configurado con: ../gcc-5.5.0/configure --prefix=/usr --libdir=/usr/lib64 --mandir=/usr/man --infodir=/usr/info --enable-shared --enable-bootstrap --enable-languages=ada,c,c++,fortran,go,java,lto,objc --enable-threads=posix --enable-checking=release --enable-objc-gc --with-system-zlib --with-python-dir=/lib64/python2.7/site-packages --enable-libstdcxx-dual-abi --with-default-libstdcxx-abi=gcc4-compatible --disable-libunwind-exceptions --enable-__cxa_atexit --enable-libssp --enable-lto --disable-install-libiberty --with-gnu-ld --verbose --enable-java-home --with-java-home=/usr/lib64/jvm/jre --with-jvm-root-dir=/usr/lib64/jvm --with-jvm-jar-dir=/usr/lib64/jvm/jvm-exports --with-arch-directory=amd64 --with-antlr-jar=/home/slackware/slackbuilds/gcc-5.5.0/antlr-runtime-3.4.jar --enable-multilib --target=x86_64-slackware-linux --build=x86_64-slackware-linux --host=x86_64-slackware-linux
Modelo de hilos: posix
gcc versión 5.5.0 (GCC)

By downloading the Slackbuild: https://slackbuilds.org/repository/14.2/libraries/libfsntfs/

3. Again, I don't get error, I dpasted you some output. It just stucks at some random point. NO ERRORS.
Looks like it compiles fine with "./configure" and "make". But some bad configure config is bad inside Slackbuild file. Something changed in newer libfsntfs releases. I just won't run "make install".

I think it is not great idea removing older releases. I just will try to modify the Slackbuild file and see what is wrong. Thanks for your help.

**Comment by joachimmetz** [comment]
> But some bad configure config is bad inside Slackbuild file.

Ok then the source is building for you. The Slackbuild file is not part of this project. You'll need to reach out to the distribution support for this, since this is out of scope for this project.

I was not even aware of the existence of the Slackbuild file. I would strongly encourage their build process to preserve the source distribution package if it dependents on it. Like what other distribution do. 

> Something changed in newer libfsntfs releases. 

"Something" definitely changed but the build process has remained the same.

> I think it is not great idea removing older releases. 

I don't think it is a great idea for people to continue using 1+ year old versions of experimental software. Or to have a distribution/build process that depends on URL to be available/not change. So I guess we agree to disagree here. 

Closing issue.
