### ISSUE TITLE
File system hierarchy traversal on 4TB live Windows volume device takes long time in customized tool

### ISSUE THREAD

**Issue by DougRogers** [libyal/libfsntfs#26]
I have a 4TB drive that takes 45 minutes to obtain the full directory history.  _fprintf_ calls have been commented out.

arguments are `-H \\.\g:`

Performance testing shows the long path in this image.  The perf test was five minutes, sampling.  Instrumenting tests did not run in Visual Studio.  It just aborted.

![image](https://user-images.githubusercontent.com/7563851/106309507-1588f880-6217-11eb-914a-01d86fc8f79a.png)

**Comment by joachimmetz** [comment]
@DougRogers you'll need to provide me with profiling data from your set up. There are many factors here:

1. as I said libfsntfs is not built with live volume devices in mind
2. without information about your test set up, the file system and actual profiling information there is not much I can do here.

**Comment by joachimmetz** [comment]
Also note if you are integrating LGPL code directly into your main application it should be licensed accordingly on distribution.

**Comment by joachimmetz** [comment]
closing issue no update from reporter
