### ISSUE TITLE
libfsntfs can not open device path like \\.\HarddiskVolume2

### ISSUE THREAD

**Issue by imagebreaker** [libyal/libfsntfs#27]
I tried to compile this project into a DLL library and referenced it in my personal project. I found a weird problem that when I opened a device path like `\\.\HarddiskVolume2`, I got an error description "libfsntfs_volume_open: unable to set filename in file IO handle". I dug in to libfsntfs_volume.c and saw the parameter name_length of the call into libbfio_file_set_name from libfsntfs_volume_open had been set to actual length of string plus 1. I could not understand the reason so I continued to read the function libbfio_file_set_name, finally I got a chain of call relationship: libbfio_file_set_name -> libcpath_path_get_full_path -> libcsplit_narrow_string_split. when splitting paths with a invalid directory index, the function returned an error. Because there were a lot of call references from the library libcpath, I didn't think I can simply fixed the only one place, so I committed a issue to you.

**Comment by joachimmetz** [comment]
First of all this project is experimental and was not designed to run on a live operating system used NTFS.

also isn't the namespace/path of the "HarddiskVolume1" supposed to be "\\Device\\HarddiskVolume1"?

**Comment by imagebreaker** [comment]
There can be a symbo link named HarddiskVolumeN in the Global?? Namespace of Windows Object Manager, so I can open a volume device by using \\.\HarddiskVolumeN to manipulate an NTFS volume. Also like \\.\PhysicalDrive0.
But the most important question is this library was not designed to run on a live operating system, so do you have any plan to parse live operating system volumes?

**Comment by joachimmetz** [comment]
> But the most important question is this library was not designed to run on a live operating system, so do you have any plan to parse live operating system volumes?

Can you explain what you exactly mean with "parse live operating system volumes".

Do mean a best effort attempt to parse data structures directly from the volume? Or do you mean a solution that takes files system changes by the operating system into account? And other run-time aspects of NTFS on Windows?

**Comment by imagebreaker** [comment]
Oh, I mean do you have any plan to parse the data structure directly from the volume device? Or I have to dump the whole volume data to a file to fit this library. Thanks for replying me.

**Comment by joachimmetz** [comment]
> Oh, I mean do you have any plan to parse the data structure directly from the volume device? 

This is (somewhat) already possible e.g. if you use `\\.\C:` instead of `\\.\HarddiskVolume2` but **not recommend** 

1. the file system can change and will while reading structures, the library does not take this into account and expects structures to be static
2. you might need to change the code to handle reading specific Windows devices, since some require special handling, such as specific IOCTL settings and sector aligned reads.

**Comment by imagebreaker** [comment]
Thanks a lot for your reply. I'll try the way you suggested.
