### ISSUE TITLE
MFT-only processing fails for MFT entry 0 with non-resident ATTRIBUTE_LIST

### ISSUE THREAD

**Issue by stbe** [libyal/libfsntfs#31]
For almost all everyday cases, this library works beautifully even on single MFTs - so if we don't have a full NTFS volume. However, in some cases, the library struggles with for example MFTs that contain non-resident `ATTRIBUTE_LIST` attributes. For those, the library fails when trying to resolve the data runs outside of the MFT. Is there any way - or any plan on the roadmap - to support the processing of single MFTs, or a way to make the processing proceed with warnings for such cases? This would also help users using plaso on artifact extracts from systems.

**Comment by stbe** [comment]
Sorry @joachimmetz, I'll try to be more specific.

> non-resident ATTRIBUTE_LIST are stored outside the $MFT metdata file

Yes, that's exactly what this is about. When processing an extracted `$MFT` that contains a non-resident `ATTRIBUTE_LIST`, the parser appears to try to resolve the contained data-run in order to find the offloaded attributes for this record. This however fails since it's outside the MFT itself, and the parser errors out with a message like the following when trying to read at the offset for the referenced cluster:

```
fsntfsinfo 20230321

Unable to open: /tmp/MFT.
libfdata_stream_read_buffer: unable to read segment: 0 data at offset: 222561685504 (0x33d1b5d000).
libfdata_stream_read_buffer_at_offset: unable to read buffer.
libfsntfs_mft_attribute_list_read_from_attribute: unable to read attribute list entry: 0 from cluster block stream at offset: 0 (0x00000000).
libfsntfs_mft_entry_read_attribute_list: unable to read attribute list.
libfsntfs_file_system_read_mft: unable to read attribute list.
libfsntfs_internal_mft_metadata_file_open_read: unable to read MFT (MFT entry: 0).
libfsntfs_volume_open_file_io_handle: unable to read from file IO handle.
info_handle_open_input: unable to open input MFT metadata file.
```

I've attached a sample to reproduce. This is not constructed scenario, but instead from a real-world system that - for some reason - has gathered enough attributes for it's record 0 (the `$MFT` itself) that the NTFS driver had to create a non-resident attribute list for it.

[MFT.gz](https://github.com/libyal/libfsntfs/files/11319820/MFT.gz)

**Comment by joachimmetz** [comment]
> Sorry @joachimmetz, I'll try to be more specific.

thanks, much appreciated, the scenario is more clear to me know. To summarize, when the first MFT entry (for $MFT itself) contains an ATTRIBUTE_LIST then the library fails to process the stand-alone $MFT file. I'll have a look later this week, when time permits. Any indication what effect this has on the $DATA runs?

**Comment by stbe** [comment]
Yes, you're correct. Although, i think it might also happen on other MFT entries, not just the first one. I think basically on any attribute that refers to data-runs outside of the $MFT. 

This would then also apply to the $DATA attribute. For example, if the library would offer a way to extract the file contents of (non-resident) $DATA attributes, and the user has only loaded the plain $MFT file, the library would probably want to resolve the data-runs in those as well and error out in similar fashion.

---
*For reference, I've tried to describe the circumstances in which this particular case might happen (anyone feel free to correct me if I'm wrong):*

I believe the scenario from the sample I've posted is a very rare one, as well as the ATTRIBUTE_LIST being a complicated one. As far as I understand the mechanics of NTFS, it first must occur that all of the attributes of an entry won't fit into one record. This can happen for example when there are too many attributes (e.g., due to lots of hard links) and/or if there are attributes with huge attribute bodies, like very fragmented data runs of a $DATA attributes. One strategy of the NTFS could be to make attribute bodies non-resident as much as possible to make enough room for all the attributes. However, that's not always possible, as attribute headers and some attribute bodies like the described data-runs cannot be made non-resident - aside from the quirk that data runs can also grow too big to fit into the record due to heavy fragmentation - so there might still not be enough room for all attributes. This is when an ATTRIBUTE_LIST is created to reference the rest of the attributes that won't fit into the record. The body of the attribute list usually carries variable length records describing where to find the rest of the attributes in the MFT. Now, if there is not enough space in the record to even describe that list, the body of the ATTRIBUTE_LIST can be made non-resident and the content is referenced by data-runs - as in the example I've posted earlier. 
[Additionally, I think there could be one more level of abstraction that can happen when the data-runs of the non-resident body of an ATTRIBUTE_LIST won't fit, then ATTRIBUTE_LIST becomes resident again, referencing two other MFT records with non-resident attribute lists describing the data runs]

**Comment by joachimmetz** [comment]
> I believe the scenario from the sample I've posted is a very rare one, as well as the ATTRIBUTE_LIST being a complicated one.

Yes MFT entry 0 having an ATTRIBUTE_LIST is not too common

```
fsntfsinfo -E 0 MFT

fsntfsinfo 20230427

MFT entry: 0 information:
	Is allocated			: true
	File reference			: 0-1
	Base record file reference	: Not set (0)
	Journal sequence number		: 238395285914
	Number of attributes		: 4
	Is corrupted

Attribute: 1
	Type				: $STANDARD_INFORMATION (0x00000010)
	Creation time			: Jan 29, 2021 23:47:34.029951000 UTC
	Modification time		: Jan 29, 2021 23:47:34.029951000 UTC
	Access time			: Jan 29, 2021 23:47:34.029951000 UTC
	Entry modification time		: Jan 29, 2021 23:47:34.029951000 UTC
	Owner identifier		: 0
	Security descriptor identifier	: 256
	Update sequence number		: 0
	File attribute flags		: 0x00000006
		Is hidden (FILE_ATTRIBUTE_HIDDEN)
		Is system (FILE_ATTRIBUTE_SYSTEM)

Attribute: 2
	Type				: $ATTRIBUTE_LIST (0x00000020)
	Data VCN range			: 0 - 63
	Data size			: 128 bytes
	Number of entries		: 0

Attribute: 3
	Type				: $FILE_NAME (0x00000030)
	Parent file reference		: 5-5
	Creation time			: Jan 29, 2021 23:47:34.029951000 UTC
	Modification time		: Jan 29, 2021 23:47:34.029951000 UTC
	Access time			: Jan 29, 2021 23:47:34.029951000 UTC
	Entry modification time		: Jan 29, 2021 23:47:34.029951000 UTC
	File attribute flags		: 0x00000006
		Is hidden (FILE_ATTRIBUTE_HIDDEN)
		Is system (FILE_ATTRIBUTE_SYSTEM)
	Name space			: DOS and Windows (3)
	Name				: $MFT
	Path hint			: \$MFT

Attribute: 4
	Type				: $DATA (0x00000080)
	Data VCN range			: 0 - 1537023
	Data size			: 6295650304 bytes
	Data flags			: 0x0000
```

**Comment by joachimmetz** [comment]
> As far as I understand the mechanics of NTFS, it first must occur that all of the attributes of an entry won't fit into one record. 

This is explained here https://osdfir.blogspot.com/2020/04/parsing-mft-ntfs-metadata-file.html

> Although, i think it might also happen on other MFT entries, not just the first one.

Have a look at scenario 3 from https://github.com/dfirlabs/ntfs-specimens/blob/main/generate-specimens-behavior-windows.bat#L211 This generated an image with an ATTRIBUTE_LIST outside MFT entry 0 (MFT entry 65 likely)

**Comment by joachimmetz** [comment]
Think have found the issue for MFT entry 0, basically it hits a code path that expects a full file system. Give the following patch a try.

```
diff --git a/libfsntfs/libfsntfs_file_system.c b/libfsntfs/libfsntfs_file_system.c
index 1669035..ec06193 100644
--- a/libfsntfs/libfsntfs_file_system.c
+++ b/libfsntfs/libfsntfs_file_system.c
@@ -529,7 +529,8 @@ int libfsntfs_file_system_read_mft(
                }
                last_data_attribute = mft_entry->data_attribute;
        }
-       if( mft_entry->list_attribute != NULL )
+       if( ( ( flags & LIBFSNTFS_FILE_ENTRY_FLAGS_MFT_ONLY ) == 0 )
+        && ( mft_entry->list_attribute != NULL ) )
        {
                if( libfsntfs_mft_entry_read_attribute_list(
                     mft_entry,
```

**Comment by stbe** [comment]
> Have a look at scenario 3 from https://github.com/dfirlabs/ntfs-specimens/blob/main/generate-specimens-behavior-windows.bat#L211 This generated an image with an ATTRIBUTE_LIST outside MFT entry 0 (MFT entry 65 likely)

Yes, that's a good example. (One side observation: the scenario3.2 does not remove the hardlinks contrary to the comment in the [script](https://github.com/dfirlabs/ntfs-specimens/blob/main/generate-specimens-behavior-windows.bat#L299))

> Think have found the issue for MFT entry 0, basically it hits a code path that expects a full file system. Give the following patch a try.

Awesome! Just gave it a spin. Can confirm, the patch does indeed fix the issue. Thanks a lot Joachim!

**Comment by joachimmetz** [comment]
> Yes, that's a good example. (One side observation: the scenario3.2 does not remove the hardlinks contrary to the comment in the [script](https://github.com/dfirlabs/ntfs-specimens/blob/main/generate-specimens-behavior-windows.bat#L299))

thx for flagging, might be a thing that needs to be completed.

**Comment by joachimmetz** [comment]
> Awesome! Just gave it a spin. Can confirm, the patch does indeed fix the issue. Thanks a lot Joachim!

thanks for confirming

**Comment by joachimmetz** [comment]
Closing issue
