### ISSUE TITLE
Getting file sizes from $MFT metadata files with pyfsntfs

### ISSUE THREAD

**Issue by segevrl** [libyal/libfsntfs#33]
Hi, I'm writing a Python parser for $MFT files using pyfsntfs, and I have some trouble getting the sizes of files. The `get_size` method of the `file_entry` object, gives me 0 for files that are not empty.
Here's an output from TSK on a [$MFT file](https://github.com/libyal/libfsntfs/files/13344559/MFT.zip) from a test image I created (entry number 61):
```
Attributes:
Type: $STANDARD_INFORMATION (16-0)   Name: N/A   Resident   size: 72
Type: $FILE_NAME (48-2)   Name: N/A   Resident   size: 92
Type: $OBJECT_ID (64-3)   Name: N/A   Resident   size: 16
Type: $DATA (128-1)   Name: N/A   Resident   size: 11
``` 
The size of the default $DATA attribute is 11 bytes. Using pyfsntfs, I get a 0:
```
>>> mft.get_file_entry(61).get_size()
0
```
Am I doing something wrong? Is there a way to get the size of the default $DATA attribute with pyfsntfs?
Thank you!

**Comment by joachimmetz** [comment]
You'll need to get the size per attribute, given that you don't have the corresponding data cluster blocks when reading only the $MFT. Also recommend having a read of https://osdfir.blogspot.com/2020/04/parsing-mft-ntfs-metadata-file.html about limited information when only reading the $MFT metadata file.

**Comment by segevrl** [comment]
Thank you! How would you get the size of an attribute with pyfsntfs? It does give me the sizes of alternate data streams, so I imagine doing this for the default $DATA attribute is also be possible. I just didn't find a function to do this.

**Comment by joachimmetz** [comment]
you need to iterate the attributes

**Comment by joachimmetz** [comment]
Have a look at https://github.com/log2timeline/plaso/blob/main/plaso/parsers/ntfs.py#L273

**Comment by segevrl** [comment]
The `attribute` object doesn't seem to have a method to get the attribute's size:
```
>>> mft.get_file_entry(61).get_attribute(3).attribute_type
128
>>>
>>> dir(mft.get_file_entry(61).get_attribute(3))
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'attribute_name', 'attribute_type', 'get_attribute_name', 'get_attribute_type']
```
I didn't see such a method in Plaso's MFT parser as well

**Comment by joachimmetz** [comment]
Could be that I had no use for it so far, and it is not implemented yet, given the project is experimental and mostly focuses on parsing the full file system.

**Comment by joachimmetz** [comment]
There is https://github.com/libyal/libfsntfs/blob/main/include/libfsntfs.h.in#L1136C5-L1136C38 which just needs to be wrapped by the Python binding, if it is missing

**Comment by segevrl** [comment]
Thanks. I'll try to add the wrapping and submit a PR. I'm not really familiar with C so I'm not sure I'll be able to do this

**Comment by joachimmetz** [comment]
thanks, I'll make a note to look into adding this when time permits, but time is limited at the moment.
