### ISSUE TITLE
Error when working with raw volumes in Windows

### ISSUE THREAD

**Issue by ohadravid** [libyal/libfsntfs#4]
Hi!

I came across this repo while trying to build a utility for raw copy of files under Windows.
I use the Python bindings, and while this works:

```
fsntfs_volume = pyfsntfs.open(r'\\.\C:')
file_entity = fsntfs_volume.get_file_entry_by_path(r'\Windows\System32\config\SAM')
data = file_entity.read(file_entity.size)
```

This will not:

```
fsntfs_volume = pyfsntfs.open(r'\\.\C:')
file_entity = fsntfs_volume.get_file_entry_by_path(r'\Windows\explorer.exe')
data = file_entity.read(file_entity.size)
# Raises OSError: pyfsntfs_file_entry_read_buffer: unable to read data. libcfile_internal_file_read_buffer_at_offset_with_error_code: unable to read from file with error: The parameter is incorrect.
```

I dug through the code, and the reason is that ReadFile fails since opening raw volumes is non-buffered and `explorer.exe` is not 512-byte aligned (and SAM is).
It goes to `libcfile_file.c:1961` which handles ERROR_INVALID_PARAMETER, but since `internal_file->block_size` is not set at any point, it just fails.

I tried calling `libcfile_file_set_block_size` myself (with size=512) and it solves it, but I was not sure where to do it and if it is the most correct thing to do (not to mention hard coding 512 seems like a bad idea).

Any way, as a workaround, this:

```
fsntfs_volume = pyfsntfs.open_file_object(open(r'\\.\C:', 'rb'))
file_entity = fsntfs_volume.get_file_entry_by_path(r'\Windows\explorer.exe')
data = file_entity.read(file_entity.size)
```

works, since it uses Python's IO, which handles the non-buffering of raw volumes correctly.

P.S
The library's code (and the rest of the dependencies) are amazing! It was a great read and they seem to work very well, and the Python binding are awesome. Thank you for it!

**Comment by joachimmetz** [comment]
use pysmdev for handling devices.

**Comment by ohadravid** [comment]
Thanks! using `pysmdev.open(r'\\.\C:')` works!
