### ISSUE TITLE
Wrong data when reading pre-allocated empty file

### ISSUE THREAD

**Issue by ohadravid** [libyal/libfsntfs#5]
Hi,

I think I found a bug.
When you try to read a completely empty file, but with pre-allocated to a size (`data_size` is 65536, for example, and `valid_data_size` is 0),
the library will ignore `valid_data_size` and read garbage from the disk.

To reproduce, Create the following file using python (I tried under Win10):

```
import os
with open('test_file', 'wb') as test_file:
    test_file.seek(64 * 1024 - 1, os.SEEK_SET)
    test_file.write(b'\0')
```

And try to read it using the library (produces random data).
You can see that `data_size` is 65536, and `valid_data_size` is 0.
(Probably `libfsntfs_cluster_block_stream.c:776` is the problem).

For reference, this file:

```
import os
with open('test_file', 'wb') as test_file:
    test_file.seek(64 * 1024 - 1, os.SEEK_SET)
    test_file.write(b'\0')
    test_file.seek(0, os.SEEK_SET)
    test_file.write(b'H')
```

Will be copied just fine (`data_size` is 65536, and `valid_data_size` is 4096).

**Comment by joachimmetz** [comment]
I'll have a look when time permits. FYI at the moment the library is still experimental.

**Comment by joachimmetz** [comment]
I've done a major overhaul recently, I opt to check the latest master to see if the issue has been addressed.

**Comment by joachimmetz** [comment]
Closing for now, reopen if issue persists
